# Generated by Django 4.2 on 2023-04-24 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Юзер ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия пользователя')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Юзернейм')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
