# Generated by Django 4.2 on 2023-04-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subcribed_to_web',
            field=models.BooleanField(default=False),
        ),
    ]
