# Generated by Django 4.2 on 2023-05-11 18:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0002_telegramuser_subcribed_to_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('message', models.CharField(max_length=5000, verbose_name='Сообщение')),
                ('hours_after_registration', models.PositiveIntegerField(default=0, verbose_name='Часы после регистрации')),
                ('content_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Медиа(фото)')),
                ('content_video', models.FileField(blank=True, null=True, upload_to='', verbose_name='Медиа(видео)')),
            ],
            options={
                'verbose_name': 'Сообщение пользователю',
                'verbose_name_plural': 'Сообщения пользователям',
            },
        ),
    ]
