# Generated by Django 4.2.1 on 2023-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0003_add_users_mesaage'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
