# Generated by Django 4.2.1 on 2023-05-26 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0004_telegramuser_onboarding_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=1000, verbose_name='CRM message id')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
