# Generated by Django 4.2.1 on 2023-05-26 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_user', '0005_crmmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
    ]
