# Generated by Django 4.2 on 2023-05-06 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='content',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='description',
        ),
        migrations.AddField(
            model_name='webinar',
            name='day_bf_content',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Медиа за день'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='day_bf_description',
            field=models.TextField(default=None, verbose_name='Описание вебинара за день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='hour_bf_content',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Медиа за час'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='hour_bf_description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание вебинара за час'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='minute_bf_content',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Медиа за 10 минут'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='minute_bf_description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание вебинара за 10 минут'),
            preserve_default=False,
        ),
    ]
