# Generated by Django 4.2 on 2023-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_remove_webinar_content_remove_webinar_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='calendar_link',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='webinar_link',
        ),
        migrations.AddField(
            model_name='webinar',
            name='day_bf_calendar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на календарь за день'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='day_bf_webinar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на вебинар за день'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='hour_bf_calendar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на календарь за час'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='hour_bf_webinar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на вебинар за час'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='minute_bf_calendar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на календарь за 10 минут'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='minute_bf_webinar_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на вебинар за 10 минут'),
        ),
    ]
