# Generated by Django 4.2.1 on 2023-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_remove_webinar_calendar_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание вебинара в вебапп'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='format',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Формат встречи'),
        ),
    ]
