# Generated by Django 4.2.1 on 2023-05-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0004_webinar_description_webinar_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='format',
            new_name='web_format',
        ),
    ]
