# Generated by Django 4.2 on 2023-05-01 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandMsg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('cmd_params', models.CharField(max_length=50, verbose_name='Параметр команды')),
                ('link', models.URLField(verbose_name='Ссылка на файл')),
                ('message', models.CharField(blank=True, max_length=3500, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
