# Generated by Django 4.2.1 on 2023-05-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandmsg',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на файл'),
        ),
    ]
